variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  image:
    name: klakegg/hugo:asciidoctor-ci
    entrypoint: ['']
  before_script:
  - apk add --no-cache git ruby
  - gem install asciidoctor-html5s
  script:
  - hugo --gc
  - gzip -k -6 $(find public -type f)
  artifacts:
    paths:
    - public
    expire_in: 1 hour
  only:
  - master
