pages:
  image:
    name: klakegg/hugo:latest
    entrypoint: ['']
  script:
    - hugo --gc --minify
    - gzip -k -9 $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - master
