pages:
  image:
    name: klakegg/hugo:latest
    entrypoint: ['']
  script:
    - hugo
    - gzip -k -9 $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
