image: ruby:slim-buster

pages:
  script:
  - gem install asciidoctor
  - gem install asciidoctor-html5s
  - sudo apt install hugo
  - hugo -D
  artifacts:
    paths:
    - public
    expire_in: 12 hours
  only:
  - master
