image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - apt update
  - apt install -y ruby
  - gem install asciidoctor
  - gem install asciidoctor-html5s
  - hugo
  artifacts:
    paths:
    - public
    expire_in: 1 hour
  only:
  - master
