image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  - gzip -k -9 -r public
  artifacts:
    paths:
    - public
  only:
  - master
