variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  image:
    name: klakegg/hugo:asciidoctor-ci
    entrypoint: ['']
  before_script:
  - apk add ruby
  - gem install asciidoctor-html5s
  script:
  - hugo
  artifacts:
    paths:
    - public
    expire_in: 1 hour
  only:
  - master
